### ISSUE TITLE
how to foder contranst/

### ISSUE THREAD

**Issue by x302502** [TaeJoongYoon/Signalus#1]

**Comment by TaeJoongYoon** [comment]
It's ignored cuz it has private URLs.

**Comment by TaeJoongYoon** [comment]
I upload all files expected private URL and html.

thanks. 😀

**Comment by x302502** [comment]
Thank you very much!

Vào Th 6, 9 thg 11, 2018 vào lúc 22:19 TaeJoong Yoon <
notifications@github.com> đã viết:
